Resources:
  GitHubSecret2:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: GitHubSecret2
      Description: AWS secrets for GitHub
      SecretString:  '{"Secretkey": "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"}'
      Tags: 
        - Key: project
          Value: new-product